<?php

/**
 * @file
 * Module file for Bene Features Example.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bene_features_example_help($route_name, RouteMatchInterface $route_match) {
  $page = NULL;
  switch ($route_name) {
    // This route is from the help module: just use the right machine name.
    case 'help.page.bene_features_example':
      $page = [
        'details' => [
          '#markup' => t('Example help page for Bene Features Example.'),
        ],
      ];
      break;

  }
  return $page;
}
